'use strict'; // code generated by pbf v3.1.0

// RequestUrl ========================================

var RequestUrl = exports.RequestUrl = {};

RequestUrl.read = function (pbf, end) {
    return pbf.readFields(RequestUrl._readField, {tiles: []}, end);
};
RequestUrl._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.tiles.push(RequestUrl.Tile.read(pbf, pbf.readVarint() + pbf.pos));
};
RequestUrl.write = function (obj, pbf) {
    if (obj.tiles) for (var i = 0; i < obj.tiles.length; i++) pbf.writeMessage(1, RequestUrl.Tile.write, obj.tiles[i]);
};

// RequestUrl.Tile ========================================

RequestUrl.Tile = {};

RequestUrl.Tile.read = function (pbf, end) {
    return pbf.readFields(RequestUrl.Tile._readField, {x: 0, y: 0, zoom: 0}, end);
};
RequestUrl.Tile._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.x = pbf.readVarint();
    else if (tag === 2) obj.y = pbf.readVarint();
    else if (tag === 3) obj.zoom = pbf.readVarint();
};
RequestUrl.Tile.write = function (obj, pbf) {
    if (obj.x) pbf.writeVarintField(1, obj.x);
    if (obj.y) pbf.writeVarintField(2, obj.y);
    if (obj.zoom) pbf.writeVarintField(3, obj.zoom);
};
